"""Downloadable 'Horus-OSINT chat' report — a branded PDF/HTML of one Q&A exchange.

The Geo-Intel chat answers are authored by the fine-tuned Horus-OSINT model (conversational,
not corpus-grounded). This renders a single question + answer into a shareable, branded
report. The PDF uses the same pure-Python Amiri/fpdf2 engine as the Arabic intelligence
report, so a correct file is produced on any OS with no system libraries — for Arabic (RTL)
or English (LTR) answers alike. Direction/shaping are decided per text block from its own
content, so an English answer to an Arabic question renders each side correctly.
"""

from __future__ import annotations

from datetime import UTC, datetime
from html import escape
from pathlib import Path

import arabic_reshaper
from bidi.algorithm import get_display
from fpdf import FPDF

_FONT_DIR = Path(__file__).resolve().parent / "fonts"
_AMIRI = _FONT_DIR / "Amiri-Regular.ttf"
_AMIRI_BOLD = _FONT_DIR / "Amiri-Bold.ttf"

_ACCENT = (13, 40, 68)
_INK = (20, 30, 48)
_MUTED = (120, 135, 160)
_PANEL = (244, 247, 252)
_LINE = (205, 214, 228)

_STR = {
    "ar": {
        "brand": "حورس سنتينل — تقرير محادثة استخباراتية",
        "slogan": "العين التي لا تنام",
        "q": "السؤال",
        "a": "إجابة حورس (Horus-OSINT)",
        "by": "التوليد بواسطة",
        "time": "التوقيت",
        "note": "استدلال النموذج — غير مُسنَد إلى المصادر المؤكدة. يلزم تحقُّق المحلل قبل الاعتماد.",
        "footer": "سرّي — للاستخدام المصرّح به فقط · صفحة",
    },
    "en": {
        "brand": "HORUS Sentinel — Intelligence Chat Report",
        "slogan": "The eye that never sleeps",
        "q": "Question",
        "a": "HORUS answer (Horus-OSINT)",
        "by": "Generated by",
        "time": "Timestamp",
        "note": "Model reasoning — not corpus-grounded. Analyst validation required before use.",
        "footer": "CONFIDENTIAL — authorized use only · page",
    },
}


def _has_arabic(s: str) -> bool:
    return any("؀" <= c <= "ۿ" or "ݐ" <= c <= "ݿ" for c in str(s))


def _shape(text: str) -> str:
    """Reshape + reorder only when the text contains Arabic; leave Latin text untouched."""
    if _has_arabic(text):
        return get_display(arabic_reshaper.reshape(str(text)))
    return str(text)


def _align(text: str) -> str:
    """Right-align Arabic blocks, left-align Latin blocks (per-block direction)."""
    return "R" if _has_arabic(text) else "L"


class _ChatPDF(FPDF):
    def __init__(self, strings: dict[str, str]) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self._s = strings
        self.set_auto_page_break(auto=True, margin=18)
        self.add_font("Amiri", "", str(_AMIRI))
        self.add_font("Amiri", "B", str(_AMIRI_BOLD))
        self.set_margins(16, 16, 16)

    def header(self) -> None:
        self.set_fill_color(*_ACCENT)
        self.rect(0, 0, self.w, 24, "F")
        self.set_xy(16, 6)
        self.set_font("Amiri", "B", 14)
        self.set_text_color(255, 255, 255)
        self.cell(
            self.w - 32, 8, _shape(self._s["brand"]), align="C", new_x="LMARGIN", new_y="NEXT"
        )
        self.set_font("Amiri", "", 9)
        self.set_x(16)
        self.cell(self.w - 32, 6, _shape(self._s["slogan"]), align="C")
        self.set_text_color(*_INK)
        self.set_y(30)

    def footer(self) -> None:
        self.set_y(-14)
        self.set_font("Amiri", "", 8)
        self.set_text_color(*_MUTED)
        self.cell(0, 8, _shape(f"{self._s['footer']} {self.page_no()}"), align="C")

    def block_label(self, text: str) -> None:
        self.ln(2)
        self.set_fill_color(*_ACCENT)
        self.set_text_color(255, 255, 255)
        self.set_font("Amiri", "B", 12)
        self.cell(0, 9, _shape(text), align="R", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*_INK)
        self.ln(1)

    def paragraph(self, text: str) -> None:
        self.set_font("Amiri", "", 11)
        self.set_text_color(*_INK)
        for para in str(text).split("\n"):
            para = para.strip()
            if not para:
                self.ln(2)
                continue
            self.multi_cell(0, 7, _shape(para), align=_align(para), new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def muted(self, text: str) -> None:
        self.set_font("Amiri", "", 9)
        self.set_text_color(*_MUTED)
        self.multi_cell(0, 6, _shape(text), align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*_INK)


def render_chat_pdf(
    question: str,
    answer: str,
    *,
    generated_by: str = "",
    language: str = "en",
) -> bytes:
    """Render one Horus-OSINT Q&A exchange to a branded PDF (bytes)."""
    s = _STR.get(language, _STR["en"])
    pdf = _ChatPDF(s)
    pdf.add_page()

    pdf.block_label(s["q"])
    pdf.paragraph(question)

    pdf.block_label(s["a"])
    pdf.paragraph(answer or "—")

    pdf.ln(2)
    ts = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    pdf.muted(f"{s['by']}: {generated_by or '—'}  ·  {s['time']}: {ts}")
    pdf.set_draw_color(*_LINE)
    pdf.set_fill_color(*_PANEL)
    y = pdf.get_y() + 1
    pdf.rect(pdf.l_margin, y, pdf.w - pdf.l_margin - pdf.r_margin, 12, "DF")
    pdf.set_xy(pdf.l_margin + 2, y + 2)
    pdf.set_font("Amiri", "", 9)
    pdf.set_text_color(180, 90, 20)
    pdf.multi_cell(pdf.w - pdf.l_margin - pdf.r_margin - 4, 5, _shape(f"⚠ {s['note']}"), align="R")
    pdf.set_text_color(*_INK)

    return bytes(pdf.output())


def render_chat_html(
    question: str,
    answer: str,
    *,
    generated_by: str = "",
    language: str = "en",
) -> str:
    """Render one Horus-OSINT Q&A exchange to a self-contained, branded HTML string."""
    s = _STR.get(language, _STR["en"])
    page_dir = "rtl" if language == "ar" else "ltr"
    ts = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    def _blk(text: str) -> str:
        d = "rtl" if _has_arabic(text) else "ltr"
        body = "".join(
            f"<p dir='{d}' style='text-align:{'right' if d == 'rtl' else 'left'}'>{escape(p)}</p>"
            for p in str(text).split("\n")
            if p.strip()
        )
        return body or "<p>—</p>"

    return f"""<!doctype html><html lang="{language}" dir="{page_dir}"><head>
<meta charset="utf-8"><title>{escape(s['brand'])}</title>
<style>
body{{font-family:'Segoe UI',Tahoma,Arial,sans-serif;color:#141e30;max-width:820px;margin:24px auto;padding:0 20px;line-height:1.7}}
header{{background:#0d2844;color:#fff;padding:18px 22px;border-radius:12px;text-align:center}}
header h1{{margin:0;font-size:20px}} header .slogan{{opacity:.85;font-size:13px;margin-top:4px}}
h2{{background:#0d2844;color:#fff;padding:8px 12px;border-radius:8px;font-size:15px;margin:22px 0 8px}}
.meta{{color:#78879f;font-size:12px;margin-top:16px}}
.note{{background:#fff3e6;border:1px solid #f0c48a;color:#8a4b0a;padding:10px 12px;border-radius:8px;font-size:13px;margin-top:8px}}
</style></head><body>
<header><h1>{escape(s['brand'])}</h1><div class="slogan">{escape(s['slogan'])}</div></header>
<h2>{escape(s['q'])}</h2>{_blk(question)}
<h2>{escape(s['a'])}</h2>{_blk(answer or '—')}
<div class="meta">{escape(s['by'])}: <code>{escape(generated_by or '—')}</code> · {escape(s['time'])}: {ts}</div>
<div class="note">⚠ {escape(s['note'])}</div>
</body></html>"""
