"""
Sign (or re-sign) an RoE record for local development/testing.

Usage:
    python -m scripts.sign_roe > examples/roe_example.json
    python -m scripts.sign_roe --domain example.com --active-scanning > my_roe.json

This is a DEV CONVENIENCE ONLY. In a real engagement, the RoE is produced
and approved out-of-band (signed engagement contract) and then encoded into
this schema + signed with the deployment's ARGUS_ROE_SIGNING_KEY by whoever
owns that key — not generated ad hoc by whoever is running jobs.
"""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime, timedelta

from core.authorization import sign_roe
from core.config import settings
from schemas.roe import RoERecord, ScopeAsset, ScopeAssetType


def build_roe(
    domain: str,
    active_scanning: bool,
    days_valid: int = 30,
) -> RoERecord:
    now = datetime.now(UTC)
    roe = RoERecord(
        client_name=f"{domain} (self-assessment)",
        authorized_by="ARGUS local dev",
        contact_email=f"security@{domain}",
        in_scope_assets=[
            ScopeAsset(type=ScopeAssetType.DOMAIN, value=domain, note="apex + all subdomains"),
        ],
        excluded_assets=[],
        active_scanning_authorized=active_scanning,
        allowed_active_tools=["nmap"] if active_scanning else [],
        valid_from=now,
        valid_until=now + timedelta(days=days_valid),
        notes="Generated by scripts/sign_roe.py for local development.",
    )
    return sign_roe(roe, settings.roe_signing_key)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--domain", default="example.com")
    parser.add_argument("--active-scanning", action="store_true")
    parser.add_argument("--days-valid", type=int, default=30)
    args = parser.parse_args()

    roe = build_roe(args.domain, args.active_scanning, args.days_valid)
    print(json.dumps(roe.model_dump(mode="json"), indent=2))


if __name__ == "__main__":
    main()
